version: "3"
services:
  template-py-rest-microservice:
    image: pyresttemplate
    ports:
      - 8000:8000
  template-py-rest-microservice:
    image: noderesttemplate
    ports:
      - 9000:9000
  template-ui-app:
    image: uiapptemplate
    ports:
      - 5000:5000
  template-ui-app-remote-1:
    image: uiremoteapptemplate1
    ports:
      - 5001:5001
  template-ui-app-remote-2:
    image: uiremoteapptemplate2
    ports:
      - 5002:5002
